# Generated by Django 2.2.1 on 2019-06-04 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0002_auto_20190604_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
