# Generated by Django 2.2.1 on 2019-06-04 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_auto_20190604_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 20, 31, 27, 601325, tzinfo=utc)),
        ),
    ]
