# Generated by Django 2.2.1 on 2019-06-05 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0004_auto_20190604_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 15, 56, 17, 212594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voted',
            name='voteFor',
            field=models.CharField(max_length=100),
        ),
    ]
